export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_USER_DETAIL_REQ = 'FETCH_USER_DETAIL_REQ';
export const FETCH_USER_DETAIL_SUC = 'FETCH_USER_DETAIL_SUCC';
export const FETCH_USER_DETAIL_ERR =  'FETCH_USER_DETAIL_ERR';